from enum import Enum


class AgentRole(str, Enum):
    CEO = "CEO"
    CTO = "CTO"
    CMO = "CMO"
    ENGINEER = "ENGINEER"


class AgentStatus(str, Enum):
    IDLE = "IDLE"
    WORKING = "WORKING"
    BLOCKED = "BLOCKED"
    OFFLINE = "OFFLINE"


class TaskStatus(str, Enum):
    TODO = "TODO"
    IN_PROGRESS = "IN_PROGRESS"
    BLOCKED = "BLOCKED"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"


class TaskType(str, Enum):
    ENGINEERING = "ENGINEERING"
    DESIGN = "DESIGN"
    TESTING = "TESTING"
    MARKETING = "MARKETING"
    RESEARCH = "RESEARCH"
    OPERATIONS = "OPERATIONS"


class MilestoneStatus(str, Enum):
    PLANNED = "PLANNED"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"


class FeatureStatus(str, Enum):
    PLANNED = "PLANNED"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"


class CompanyStatus(str, Enum):
    CREATED = "CREATED"
    RUNNING = "RUNNING"
    PAUSED = "PAUSED"
    FAILED = "FAILED"
    COMPLETED = "COMPLETED"


class GoalStatus(str, Enum):
    TODO = "TODO"
    IN_PROGRESS = "IN_PROGRESS"
    ACHIEVED = "ACHIEVED"
    CANCELLED = "CANCELLED"


class ProjectStatus(str, Enum):
    PLANNED = "PLANNED"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"


class CustomerStatus(str, Enum):
    ACTIVE = "ACTIVE"
    CHURNED = "CHURNED"


class EventType(str, Enum):
    COMPANY_CREATED = "COMPANY_CREATED"
    AGENT_SPAWNED = "AGENT_SPAWNED"
    SIMULATION_STARTED = "SIMULATION_STARTED"
    SIMULATION_PAUSED = "SIMULATION_PAUSED"
    TICK = "TICK"
    OBSERVE = "OBSERVE"
    THINK = "THINK"
    DECIDE = "DECIDE"
    ACT = "ACT"
    REFLECT = "REFLECT"
    DECISION = "DECISION"
    GOAL_CREATED = "GOAL_CREATED"
    TASK_CREATED = "TASK_CREATED"
    CUSTOM = "CUSTOM"
    # Phase 3 simulation events
    MARKET_UPDATE = "MARKET_UPDATE"
    ENVIRONMENTAL_EVENT = "ENVIRONMENTAL_EVENT"
    CUSTOMER_ACQUIRED = "CUSTOMER_ACQUIRED"
    CUSTOMER_CHURNED = "CUSTOMER_CHURNED"
    FINANCIAL_SUMMARY = "FINANCIAL_SUMMARY"
    GOAL_PROGRESS = "GOAL_PROGRESS"
    PRODUCT_PROGRESS = "PRODUCT_PROGRESS"
    COMPANY_FAILED = "COMPANY_FAILED"
    COMPANY_COMPLETED = "COMPANY_COMPLETED"
    # Phase 4 work execution events
    TASK_STARTED = "TASK_STARTED"
    TASK_BLOCKED = "TASK_BLOCKED"
    TASK_UNBLOCKED = "TASK_UNBLOCKED"
    TASK_COMPLETED = "TASK_COMPLETED"
    MILESTONE_COMPLETED = "MILESTONE_COMPLETED"
    FEATURE_COMPLETED = "FEATURE_COMPLETED"
    PRODUCT_QUALITY_UPDATE = "PRODUCT_QUALITY_UPDATE"
    TECHNICAL_DEBT_INCREASED = "TECHNICAL_DEBT_INCREASED"
    # Phase 5 autonomy events
    PLAN_CREATED = "PLAN_CREATED"
    PLAN_REVISED = "PLAN_REVISED"
    PLAN_COMPLETED = "PLAN_COMPLETED"
    PLAN_FAILED = "PLAN_FAILED"
    EXPECTATION_CREATED = "EXPECTATION_CREATED"
    EXPECTATION_MET = "EXPECTATION_MET"
    EXPECTATION_MISSED = "EXPECTATION_MISSED"
    MESSAGE_SENT = "MESSAGE_SENT"
    MESSAGE_RECEIVED = "MESSAGE_RECEIVED"
    BLOCKER_REPORTED = "BLOCKER_REPORTED"
    BLOCKER_ESCALATED = "BLOCKER_ESCALATED"
    BLOCKER_RESOLVED = "BLOCKER_RESOLVED"
    DECISION_EVALUATED = "DECISION_EVALUATED"
    LESSON_LEARNED = "LESSON_LEARNED"
    # Phase 6 market & strategy events
    PRICE_CHANGED = "PRICE_CHANGED"
    TARGET_SEGMENT_CHANGED = "TARGET_SEGMENT_CHANGED"
    POSITIONING_CHANGED = "POSITIONING_CHANGED"
    CAMPAIGN_CREATED = "CAMPAIGN_CREATED"
    CAMPAIGN_COMPLETED = "CAMPAIGN_COMPLETED"
    SALES_OPPORTUNITY_CREATED = "SALES_OPPORTUNITY_CREATED"
    SALES_OPPORTUNITY_WON = "SALES_OPPORTUNITY_WON"
    SALES_OPPORTUNITY_LOST = "SALES_OPPORTUNITY_LOST"
    COMPETITOR_ACTION = "COMPETITOR_ACTION"
    MARKET_SHARE_CHANGED = "MARKET_SHARE_CHANGED"
    STRATEGIC_EXPECTATION_MISSED = "STRATEGIC_EXPECTATION_MISSED"
    # Phase 7 LLM cognition events
    LLM_DECISION_REQUESTED = "LLM_DECISION_REQUESTED"
    LLM_DECISION_RECEIVED = "LLM_DECISION_RECEIVED"
    LLM_DECISION_FAILED = "LLM_DECISION_FAILED"
    LLM_DECISION_RETRIED = "LLM_DECISION_RETRIED"
    # Phase 9 workforce events
    JOB_OPENED = "JOB_OPENED"
    CANDIDATE_GENERATED = "CANDIDATE_GENERATED"
    CANDIDATE_EVALUATED = "CANDIDATE_EVALUATED"
    EMPLOYEE_HIRED = "EMPLOYEE_HIRED"
    EMPLOYEE_ONBOARDED = "EMPLOYEE_ONBOARDED"
    EMPLOYEE_PROMOTED = "EMPLOYEE_PROMOTED"
    EMPLOYEE_PERFORMANCE_UPDATED = "EMPLOYEE_PERFORMANCE_UPDATED"
    EMPLOYEE_AT_RISK = "EMPLOYEE_AT_RISK"
    EMPLOYEE_TERMINATED = "EMPLOYEE_TERMINATED"
    WORKFORCE_CAPACITY_CHANGED = "WORKFORCE_CAPACITY_CHANGED"
    # Phase 10 financial events
    FUNDING_ROUND_CREATED = "FUNDING_ROUND_CREATED"
    INVESTOR_CONTACTED = "INVESTOR_CONTACTED"
    PIPELINE_ADVANCED = "PIPELINE_ADVANCED"
    INVESTMENT_DECIDED = "INVESTMENT_DECIDED"
    BUDGET_REQUESTED = "BUDGET_REQUESTED"
    BUDGET_APPROVED = "BUDGET_APPROVED"
    BUDGET_REJECTED = "BUDGET_REJECTED"
    FINANCIAL_DISTRESS = "FINANCIAL_DISTRESS"
    # Phase 11 operational events
    OBJECTIVE_CREATED = "OBJECTIVE_CREATED"
    OBJECTIVE_UPDATED = "OBJECTIVE_UPDATED"
    OBJECTIVE_ACHIEVED = "OBJECTIVE_ACHIEVED"
    OBJECTIVE_CANCELLED = "OBJECTIVE_CANCELLED"
    RESOURCE_ALLOCATED = "RESOURCE_ALLOCATED"
    RESOURCE_CONSTRAINED = "RESOURCE_CONSTRAINED"
    PRIORITY_CHANGED = "PRIORITY_CHANGED"
    RISK_DETECTED = "RISK_DETECTED"
    RISK_RESOLVED = "RISK_RESOLVED"
    RISK_ESCALATED = "RISK_ESCALATED"
    INCIDENT_CREATED = "INCIDENT_CREATED"
    INCIDENT_ESCALATED = "INCIDENT_ESCALATED"
    INCIDENT_RESOLVED = "INCIDENT_RESOLVED"
    WORK_REASSIGNED = "WORK_REASSIGNED"
    WORK_PAUSED = "WORK_PAUSED"
    WORK_RESUMED = "WORK_RESUMED"


class EnvironmentEventType(str, Enum):
    """Types of environmental events that can affect a company."""

    MARKET_BOOM = "MARKET_BOOM"
    MARKET_DOWNTURN = "MARKET_DOWNTURN"
    COMPETITOR_LAUNCH = "COMPETITOR_LAUNCH"
    CUSTOMER_SURGE = "CUSTOMER_SURGE"
    CUSTOMER_DECLINE = "CUSTOMER_DECLINE"
    INFRASTRUCTURE_COST_INCREASE = "INFRASTRUCTURE_COST_INCREASE"
    # Phase 6 strategic events
    COMPETITOR_PRICE_DROP = "COMPETITOR_PRICE_DROP"
    MARKET_EXPANSION = "MARKET_EXPANSION"
    MARKET_CONTRACTION = "MARKET_CONTRACTION"
    CUSTOMER_TREND_SHIFT = "CUSTOMER_TREND_SHIFT"
    REGULATORY_PRESSURE = "REGULATORY_PRESSURE"
    TECHNOLOGY_SHIFT = "TECHNOLOGY_SHIFT"


# --- Phase 5: Autonomy enums ---


class PlanStatus(str, Enum):
    ACTIVE = "ACTIVE"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class MemoryType(str, Enum):
    FACT = "FACT"
    DECISION = "DECISION"
    OUTCOME = "OUTCOME"
    LESSON = "LESSON"
    PREFERENCE = "PREFERENCE"
    WARNING = "WARNING"
    RELATIONSHIP = "RELATIONSHIP"


class MessagePriority(str, Enum):
    LOW = "LOW"
    NORMAL = "NORMAL"
    HIGH = "HIGH"
    URGENT = "URGENT"


class ExpectationStatus(str, Enum):
    PENDING = "PENDING"
    MET = "MET"
    MISSED = "MISSED"
    PARTIAL = "PARTIAL"


class DecisionEvaluation(str, Enum):
    SUCCESSFUL = "SUCCESSFUL"
    PARTIAL = "PARTIAL"
    INEFFECTIVE = "INEFFECTIVE"
    FAILED = "FAILED"
    UNKNOWN = "UNKNOWN"


# --- Phase 6: Market & Strategy enums ---


class SegmentType(str, Enum):
    SMB = "SMB"
    MID_MARKET = "MID_MARKET"
    ENTERPRISE = "ENTERPRISE"
    STARTUP = "STARTUP"


class CompetitorStrategy(str, Enum):
    LOW_COST = "LOW_COST"
    PREMIUM = "PREMIUM"
    GROWTH = "GROWTH"
    ENTERPRISE = "ENTERPRISE"
    BALANCED = "BALANCED"


class SalesStage(str, Enum):
    LEAD = "LEAD"
    QUALIFIED = "QUALIFIED"
    PROPOSAL = "PROPOSAL"
    WON = "WON"
    LOST = "LOST"


class CampaignStatus(str, Enum):
    ACTIVE = "ACTIVE"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"


# --- Phase 9: Workforce enums ---


class EmployeeStatus(str, Enum):
    CANDIDATE = "CANDIDATE"
    INTERVIEWING = "INTERVIEWING"
    OFFERED = "OFFERED"
    ONBOARDING = "ONBOARDING"
    ACTIVE = "ACTIVE"
    UNDERPERFORMING = "UNDERPERFORMING"
    TERMINATED = "TERMINATED"
    RESIGNED = "RESIGNED"


class JobStatus(str, Enum):
    OPEN = "OPEN"
    FILLED = "FILLED"
    CANCELLED = "CANCELLED"


class PerformanceRating(str, Enum):
    STRONG = "STRONG"
    HEALTHY = "HEALTHY"
    AT_RISK = "AT_RISK"
    UNDERPERFORMING = "UNDERPERFORMING"


# --- Phase 10: Financial Intelligence, Funding & Capital Management ---


class FinancialHealth(str, Enum):
    HEALTHY = "HEALTHY"
    AT_RISK = "AT_RISK"
    CRITICAL = "CRITICAL"
    FAILED = "FAILED"


class FundingRoundStatus(str, Enum):
    DISCOVERED = "DISCOVERED"
    CONTACTED = "CONTACTED"
    INTERESTED = "INTERESTED"
    DUE_DILIGENCE = "DUE_DILIGENCE"
    OFFERED = "OFFERED"
    INVESTED = "INVESTED"
    PASSED = "PASSED"


class BudgetStatus(str, Enum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    ALLOCATED = "ALLOCATED"


class InvestorStage(str, Enum):
    PRE_SEED = "PRE_SEED"
    SEED = "SEED"
    SERIES_A = "SERIES_A"
    SERIES_B = "SERIES_B"


# --- Phase 11: Advanced Autonomous Company Operations ---


class ObjectiveStatus(str, Enum):
    TODO = "TODO"
    IN_PROGRESS = "IN_PROGRESS"
    ACHIEVED = "ACHIEVED"
    CANCELLED = "CANCELLED"


class ObjectiveType(str, Enum):
    STRATEGIC = "STRATEGIC"
    DEPARTMENT = "DEPARTMENT"
    OPERATIONAL = "OPERATIONAL"


class ResourceType(str, Enum):
    CASH = "CASH"
    ENGINEERING_CAPACITY = "ENGINEERING_CAPACITY"
    MARKETING_BUDGET = "MARKETING_BUDGET"
    SALES_CAPACITY = "SALES_CAPACITY"
    MANAGEMENT_ATTENTION = "MANAGEMENT_ATTENTION"


class RiskStatus(str, Enum):
    ACTIVE = "ACTIVE"
    MITIGATING = "MITIGATING"
    RESOLVED = "RESOLVED"
    ESCALATED = "ESCALATED"


class RiskSeverity(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class IncidentStatus(str, Enum):
    ACTIVE = "ACTIVE"
    MITIGATING = "MITIGATING"
    RESOLVED = "RESOLVED"
    ESCALATED = "ESCALATED"


class IncidentType(str, Enum):
    RUNWAY_CRISIS = "RUNWAY_CRISIS"
    PRODUCT_DELAY = "PRODUCT_DELAY"
    CUSTOMER_CHURN_SPIKE = "CUSTOMER_CHURN_SPIKE"
    COMPETITIVE_THREAT = "COMPETITIVE_THREAT"
    WORKFORCE_SHORTAGE = "WORKFORCE_SHORTAGE"
    QUALITY_CRISIS = "QUALITY_CRISIS"
    SALES_PIPELINE_CRISIS = "SALES_PIPELINE_CRISIS"
    TECHNICAL_DEBT_CRISIS = "TECHNICAL_DEBT_CRISIS"
    MARKET_CONTRACTION_CRISIS = "MARKET_CONTRACTION_CRISIS"


# --- Phase 16: Scenario & Experiment enums ---


class ScenarioStatus(str, Enum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
